debugging

diff --git a/.github/workflows/back-pr.yml b/.github/workflows/back-pr.yml
--- a/.github/workflows/back-pr.yml
+++ b/.github/workflows/back-pr.yml
@@ -35,8 +35,13 @@ jobs:
           git push -f -u origin $NEW_BRANCH_NAME
           TITLE=$(echo "${{ github.event.pull_request.title }}" | sed 's/"/\\"/g')
           BODY=$(echo "${{ github.event.pull_request.body }}" | sed 's/"/\\"/g')
-          if $((gh pr create -B ${{ inputs.branch_name }} -H "$NEW_BRANCH_NAME" --title "$TITLE" --body "$BODY") 2>&1 ) | grep -q "a pull request for branch \"$NEW_BRANCH_NAME\" into branch \"${{ inputs.branch_name }}\" already exists"; then
+          PR_OUTPUT=$(gh pr create -B ${{ inputs.branch_name }} -H "$NEW_BRANCH_NAME" --title "$TITLE" --body "$BODY" 2>&1) || true
+          echo "PR_OUTPUT: $PR_OUTPUT"
+          if echo "$PR_OUTPUT" | grep -q "a pull request for branch \"$NEW_BRANCH_NAME\" into branch \"${{ inputs.branch_name }}\" already exists"; then
             echo "PR already exists"
+          else
+            echo "Failed to create pull request."
+            exit 1
           fi
         env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
