check for validation failures

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,10 +37,12 @@ jobs:
           sf sgd source delta --to "HEAD" --from "HEAD^" -o "." -i .forceignore
           echo "Validating..."
           OUTPUT=$(sf project deploy validate -x package/package.xml -l RunLocalTests -w 30 2>&1) || true
-          STATUS=$?
           echo "Done"
           echo "$OUTPUT"
           if echo "$OUTPUT" | grep -c "No local changes to deploy"; then
             exit 0
+          elif echo "$OUTPUT" | grep -c "Failed to validate the deployment"; then
+            exit 1
+          else
+            exit 0
           fi
-          exit $STATUS
