determine result based on output

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,17 +34,14 @@ jobs:
 
       - name: "Validate Build and Run Tests"
         run: |
-          OUTPUT=$(sf sgd source delta --to "HEAD" --from "HEAD^" -o "." -i .forceignore 2>&1)
-          if echo "$OUTPUT" | grep -q "Success"; then
-            echo "Delta generation successful"
-            echo "$OUTPUT"
-          elif echo "$OUTPUT" | grep -q "No local changes to deploy."; then
+          sf sgd source delta --to "HEAD" --from "HEAD^" -o "." -i .forceignore
+          OUTPUT=$(sf project deploy validate -x package/package.xml -l RunLocalTests -w 30 2>&1)
+          if echo "$OUTPUT" | grep -q "Error (NothingToDeploy): No local changes to deploy"; then
             echo "No changes to deploy - continuing workflow"
-            echo "$OUTPUT"
             exit 0
           else
-            echo "Delta generation failed with an error"
             echo "$OUTPUT"
-            exit 1
+            if [[ $? -ne 0 ]]; then
+              exit 1
+            fi
           fi
-          sf project deploy validate -x package/package.xml -l RunLocalTests -w 30
